# Generated by Django 4.2.6 on 2023-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_featuredbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="font_color",
            field=models.CharField(default="black", max_length=128),
        ),
    ]
